### PR TITLE
Peifeng has phinished

### PR DESCRIPTION
**Pull request by mosharaf**
Yay!

### CODE REVIEW

**Comment by jaywonchung** [comment]
Whoo! But maybe preserve the link to his homepage?

**Comment by mosharaf** [comment]
Hmm. I removed it (and juncheng's before) because it may become out of date or abandoned at some point.

**Comment by Aetf** [comment]
I intend to keep it alive, even though I haven't been posting articles on it for quite a while :laughing:

**Comment by insujang** [comment]
[Juncheng's webpage](https://gujuncheng.info) is also alive, but doesn't seem to be maintained after his graduation. Maybe we can use his [Linkedin profile](https://www.linkedin.com/in/juncheng-gu-93960859/).

**Comment by mosharaf** [comment]
All good points, but I want something consistent. LinkedIn is a good compromise as it has a summary of all info (everyone has to update it every few years to look for jobs). I don't like something that cannot be maintained long term. Student website, linkedin or otherwise, is a prime example of that. Soon we'll have a mix of live link, dead link, and no link. No link is guaranteed to be static. For example,  I already don't like that  @singam-sanjay doesn't have a webpage linked.

**Comment by jaywonchung** [comment]
Yeah LinkedIn sounds good to me. @Aetf

**Comment by mosharaf** [comment]
Let's try for a few days. I'm certain we'll default to no link as people won't maintain updated info. For  example, Juncheng's LinkedIn already says PhD till 2020! 

That's why we have everyone's first hop after PhD, which is also static

**Comment by mosharaf** [comment]
It seems @Aetf's linkedin is also stale.

Anything live requires continuous maintenance :|

**Review by jaywonchung — APPROVED** [review]
I surrender. Static makes sense 👍

**Comment by insujang** [comment]
I have no idea whether there is a way of maintaining all students' website links all up-to-date automatically. We can manage them but with manual effort, and for now it won't be bothersome but will grow over time. In terms of consistency, no-link is the king for sure.

However, I think having a well-managed website is still important even after graduation for their career, and asking to maintain websites to alumni would also be good for our group since it can give some impression to visitors that people from here are doing self-management well. [Ion's homepage](http://people.eecs.berkeley.edu/~istoica/) is a good example; although some links are stale, it looks to be very well maintained (maybe it is because many of his students are professors now, but anyway). I hope we could have a talk regarding this in our group meeting. :)

**Review by insujang — APPROVED** [review]

**Comment by Aetf** [comment]
> It seems @Aetf's linkedin is also stale.

I'm waiting until actually start working to update that. I don't even know how to describe what I do now :shrug:

**Pull request merged**
