### PR TITLE
Pack menu items together a bit

### PR DESCRIPTION
**Pull request by jaywonchung**
Before:
Screen Shot 2023-02-21 at 5 04 00 PM
After:
Screen Shot 2023-02-21 at 5 04 23 PM

### CODE REVIEW

**Comment by mosharaf** [comment]
Can we center align vertically? What was it like before?

**Comment by jaywonchung** [comment]
Centering vertically will look like this. It was not centered before.
Screen Shot 2023-02-21 at 5 58 11 PM

**Comment by jaywonchung** [comment]
Together with content:
Screen Shot 2023-02-21 at 6 00 29 PM
Screen Shot 2023-02-21 at 5 59 36 PM

**Comment by mosharaf** [comment]
Thanks @jaywonchung Let's keep bottom aligned.

**Review by mosharaf — APPROVED** [review]

**Pull request merged**
