### PR TITLE
Add oobleck

### PR DESCRIPTION
**Pull request by insujang**
#202

First a version without badges. Will create another PR when we get it.

### CODE REVIEW

**Comment by jaywonchung** [comment]
I'm not sure if we typically post intermediate versions in our pubs section. I've lost confidence about my decision after the "Chase-incident" last March 😅  @mosharaf

**Comment by jaywonchung** [comment]
My opinion is that most people look at the paper just once when they get a Google Scholar Alert (which will be triggered soon when this PR gets merged), so most will never see the version with the badges.

**Comment by mosharaf** [comment]
No one cares about the badges

**Comment by insujang** [comment]
Google Scholar just maintains a link to the PDF; after updating the PDF with badges, they will see the PDF with badges, since the link doesn't change.

**Comment by jaywonchung** [comment]
Also, are we sure we want to add a new "Fault Tolerance" publist topic?

**Comment by mosharaf** [comment]
We don't want to

**Review by jaywonchung — COMMENTED** [review]
Please remove the Fault Tolerance publist topic, and as you change that, end the file with a newline to make POSIX happy :)

**Comment by insujang** [comment]
Removed. Thanks for checking!

**Review by jaywonchung — APPROVED** [review]
LGTM!

**Pull request merged**
