### PR TITLE
fedtrans mlsys'24

### PR DESCRIPTION
**Pull request by AmberLJC**

### CODE REVIEW

**Comment by AmberLJC** [comment]
#243

**Comment by AmberLJC** [comment]
@mosharaf Manually ask for review

**Review by mosharaf — CHANGES_REQUESTED** [review]
Put FedTrans inside a bracket in the bib file so the capitalization holds when someone copies it later.

**Comment by AmberLJC** [comment]
Do you mean '@InProceedings{FedTrans:mlsys24, ...'?
Just added it

**Comment by AmberLJC** [comment]
Okay! please check it out

**Review by mosharaf — APPROVED** [review]

**Pull request merged**
