### PR TITLE
AutoPS arXiv

### PR DESCRIPTION
**Pull request by mosharaf**

### CODE REVIEW

**Review by insujang — APPROVED** [review]

**Comment by jaywonchung** [comment]
From first sight this doesn't look like "disaggregation" to me. Can you double check just in case?

**Comment by mosharaf** [comment]
@jaywonchung good point. I thought about it. Juncheng described as so in his dissertation from the point of view that instead of every job having separate PS, this provides a shared PS for all jobs, which will lead to better memory and CPU utilization. But it's a stretch.

**Comment by mosharaf** [comment]
I took it off.

**Comment by jaywonchung** [comment]
Would people who select the "disaggregation" topic manually in our website want to see this?

**Comment by jaywonchung** [comment]
Oh okay. Merging!

**Comment by mosharaf** [comment]
Agreed. I removed Disaggregation.

**Pull request merged**
