### PR TITLE
add badges to Oobleck

### PR DESCRIPTION
**Pull request by insujang**
#202 , adding badges

### CODE REVIEW

**Review by jaywonchung — APPROVED** [review]
LGTM!

**Comment by mosharaf** [comment]
:)

I'm guessing they have a way to serialize and ignore. What would've happened if I approved, and you disapproved?

**Comment by jaywonchung** [comment]
I think whether the PR can still be merged depends on many things, including whether the `develop` branch is set as protected (i.e., no commits can append without PR approvals), whether I have the member permissions to *dismiss* reviews, etc :)

**Comment by insujang** [comment]
If approval and merge happen before a request to change is created, I guess the request fails as it is already merged.
If request is added before merge, even with an approval the request still anyway needs to be handled, so merging would be blocked before solving it. Not sure though.

**Pull request merged**
