### PR TITLE
Homepage content renewal

### LINKED ISSUE #144: Add a Join Us page

### PR DESCRIPTION
**Pull request by jaywonchung**
This PR intends to make the content of our homepage up to date for the next application cycle.

Changes
- Menu bar
  - **Projects -> Research.** I'm debating between `fa-code` vs `fa-lightbulb` for the icon. Feel free to suggest something better. https://fontawesome.com/v5/search?o=r&m=free
  - **Removed Wiki.** The Wiki is an internal thing. Everyone except a dozen people in the universe face a blunt you-are-unauthorized screen.
  - **Added Join us.** The menu bar seems slightly short without the Wiki, and the Join us sentence in the front page may not be enough. People might decide to join while looking at the research tab, too!
  - Preview: Screen Shot 2022-09-10 at 3 16 00 PM

- Content
  - Reflects what we finalized in the Google Doc.
- Misc
  - Removed duplicate image `source/projects/image/latency_domain.png`. Invoking `diff` between that and `assets/latency_domain.png` returns 0.

Before merging:
- [ ] Update the number of open positions in the Join us form.

Closes #144.

### CODE REVIEW

**Comment by mosharaf** [comment]
LGTM.

Lightbulb sounds good; would be better if the bulb had some dashes around showing light coming out though

**Comment by jaywonchung** [comment]
Yeah that one is a paid icon haha. Then code vs lightbulb?

**Comment by mosharaf** [comment]
code is fine then

**Comment by jaywonchung** [comment]
Oh okay. Then feel free to merge whenever the form is ready.

**Review by mosharaf — APPROVED** [review]

**Comment by mosharaf** [comment]
I've removed the number of open positions altogether from the form and added an optional transcripts upload box in the form.

**Pull request merged**
