### PR TITLE
Add justitia pdf and code

### PR DESCRIPTION
**Pull request by yiwenzhang92**

### CODE REVIEW

**Comment by mosharaf** [comment]
Fix the conflict

**Review by Aetf — CHANGES_REQUESTED** [review]
@yiwenzhang92 I already merged your previous PR. So you should pull latest develop branch and start from there. Then there won't be conflicts

**Review by Aetf — APPROVED** [review]
Ok, that also works

**Comment by yiwenzhang92** [comment]
Thanks Peifeng

**Pull request merged**
