### PR TITLE
add Kayak paper

### LINKED ISSUE #33: Kayak in pubs

### PR DESCRIPTION
**Pull request by jimmyyou**
Uploading Kayak paper. Fixes #33

### CODE REVIEW

**Review by Aetf — CHANGES_REQUESTED** [review]
The pdf file is empty? (You can directly push to your branch and the PR will update)

**Comment by Aetf** [comment]
You forgot to include a new conference definition in `publications/index.md`

**Comment by jimmyyou** [comment]
Adding a new conference now. I closed my last PR, and can not reopen it so I had to create a new PR (even though I had force pushed).

**Review by Aetf — COMMENTED** [review]
LGTM. Note that the entry won't show up on the website yet because the conference date is in the future

**Review by Aetf — APPROVED** [review]

**Pull request merged**
