### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by mosharaf**

### CODE REVIEW

**Comment by insujang** [comment]
@mosharaf Will the entire list of the students are automatically numbered if we just change the first element to 1?

**Comment by mosharaf** [comment]
Hmm. It doesn't here but should've worked with proper markdown. Let me number them by hand!

**Comment by mosharaf** [comment]
We should figure out whether it works, and if not how to make it work. Locally it didn't so I pushed a manual numbering for now.

**Comment by insujang** [comment]
https://widatama.github.io/hexo-jade-starter/markdown-syntax/#list

It seems we can use any numbers to generate a numbered list like:
```
1. [Jie You](https://web.eecs.umich.edu/~jieyou/)
1. [Hasan Al Maruf](https://web.eecs.umich.edu/~hasanal/)
1. [Fan Lai](http://www-personal.umich.edu/~fanlai/)
```
or
```
3. [Jie You](https://web.eecs.umich.edu/~jieyou/)
1. [Hasan Al Maruf](https://web.eecs.umich.edu/~hasanal/)
7. [Fan Lai](http://www-personal.umich.edu/~fanlai/)
```

which will generate the exact same following html:

```
<ol>
  <li>...</li>
  <li>...</li>
</ol>
```
```
1. [Jie You](https://web.eecs.umich.edu/~jieyou/)
2. [Hasan Al Maruf](https://web.eecs.umich.edu/~hasanal/)
3. [Fan Lai](http://www-personal.umich.edu/~fanlai/)
```

**Review by insujang — APPROVED** [review]
Approve manual numbering, but please feel free to use any numbers for list elements.

**Pull request merged**
