### PR TITLE
2016 and 2017

### PR DESCRIPTION
**Pull request by mosharaf**

### CODE REVIEW

**Comment by juncgu** [comment]
`Fast and Accurate Performance Analysis of LTE Radio Access Networks` (2016) is not there. We may add a new `Arxiv` (or `preprint`) category for it, other than `Conference` and `Journal`.

**Comment by mosharaf** [comment]
I only did the published ones. We can do all technical reports later
together.

**Comment by juncgu** [comment]
Thanks.
The pull request looks good and is ready to merge.

**Review by Aetf — APPROVED** [review]
Looks good. The CI error is irrelevant. I'll merge this.

**Pull request merged**
